### PR TITLE
Dhivehi language added

### PR DESCRIPTION
**Pull request by xahiru**
Since Dhivehi is a right-to-left language, webapp's css and layout needs to be changed.

### CODE REVIEW

**Comment by or-else** [comment]
I have no experience with RTL languages and it's not clear to me what I have to change in the css. Would you mind advising me on CSS changes? Thanks!

**Comment by xahiru** [comment]
Hi, I'm not very good at CSS. In general, all the text should float to right and the icons should be on the left size. Also, it's better have the chat panel on the left and users/login panel on the right.  I'll try to rewrite css for the whole app and do a new pull request.

**Comment by or-else** [comment]
As far as I understand, the root `<html>` should be updated with `dir="rtl"` languages like this: `<html dir="rtl">`, and a lot of css classes should have `dir="auto"`.

**Comment by or-else** [comment]
Please do not delete `.gitignore` and `firebase-init.js`. They are both needed. Thanks!

**Comment by or-else** [comment]
Is this PR abandoned?

**Pull request closed without merging**
