### PR TITLE
Message editing, video messages

### PR DESCRIPTION
**Pull request by or-else**

### CODE REVIEW

**Comment by aforge** [comment]
Here are some issues:
* Editing should not be allowed on messages containing a quote `QQ`.
* Start editing a message (but do not finish), and go to another topic. It should clear the text bar.
* Download a video from preview. It saves the video file locally under the ref name (e.g. `K5dHwMx7O5g.bin`), not original name.
* Posting a small video (suitable to be sent inline):
```
Uncaught (in promise) TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.all (<anonymous>)
    at MessagesView.sendVideoAttachment (messages-view.jsx:1015:15)
    at video-preview.jsx:33:31
```
(Note: I increased `max_message_size` in the server config and user this file:
https://user-images.githubusercontent.com/45520561/210642111-c2320599-0235-4abc-98f3-a234d7ac8a26.mp4)

* Inline videos won't play (posted the above video file from iOS)

**Comment by or-else** [comment]
> Editing should not be allowed on messages containing a quote QQ.

fixed

> Start editing a message (but do not finish), and go to another topic. It should clear the text bar.

fixed

> Download a video from preview. It saves the video file locally under the ref name (e.g. K5dHwMx7O5g.bin), not original name.

That's a problem for everything. Downloading no longer works for any large files: 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a 

_download only works for [same-origin URLs](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy), or the blob: and data: schemes._

In our case large files and media are served through redirect to aws, and consequently Chrome ignores 'download' attribute, including the suggested file name. So, the current broken behavior is the best option.

**Comment by or-else** [comment]
Inline videos: working on it.

**Comment by aforge** [comment]
> > Start editing a message (but do not finish), and go to another topic. It should clear the text bar.
> 
> fixed

It appears that the internal "Editing" state is not fully cleared.
Start editing, go to another topic, type some text in the input bar and post. The message appears as edited.
web-0

> 
> > Download a video from preview. It saves the video file locally under the ref name (e.g. K5dHwMx7O5g.bin), not original name.
> 
> That's a problem for everything. Downloading no longer works for any large files: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a
> 
> _download only works for [same-origin URLs](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy), or the blob: and data: schemes._
> 
> In our case large files and media are served through redirect to aws, and consequently Chrome ignores 'download' attribute, including the suggested file name. So, the current broken behavior is the best option.
> 
> We may try to solve it like this though: https://engineering.resolvergroup.com/2022/02/aws-s3-utf-8-content-disposition/

I see. Let's keep it as is.

**Comment by or-else** [comment]
> Posting a small video (suitable to be sent inline):

fixed

> Inline videos won't play (posted the above video file from iOS)

fixed

> It appears that the internal "Editing" state is not fully cleared.

fixed

**Comment by aforge** [comment]
That's all good.
The forwarded video message preview in the send message bar appears broken.
web-1

**Comment by or-else** [comment]
> The forwarded video message preview in the send message bar appears broken.

fixed

**Review by aforge — APPROVED** [review]
Looking good. Thanks!

**Comment by piratov** [comment]
Loading stuck
image

**Comment by piratov** [comment]
> Loading stuck image

After refreshing the page F5 or moving to another group
image

**Pull request merged**
